### ISSUE TITLE
white web sdk repo?

### ISSUE THREAD

**Issue by luke** [netless-io/window-manager#12]
Hi, I see this uses white-web-sdk but I can't seem to find the source on GitHub, the npm package points to https://github.com/duty-os/white-sdk but that gives a 404. Package is marked as MIT

Thanks for any help :)

**Comment by hyrious** [comment]
`white-web-sdk` is not open sourced, sorry. The `mit` is a mistake in its package.json. We will fix that in the next release.

That package has a document which you can find in its readme.
