### ISSUE TITLE
WindowManager.isCreated being set true

### ISSUE THREAD

**Issue by parallelmedical** [netless-io/window-manager#5]
Im finding that when mounting WindowManager it "sometimes" fails due to the WindowManager.isCreated property being True.

if (WindowManager.isCreated) {        
           throw new Error("[WindowManager]: Already created cannot be created again");
 }

the property is supposed to be set true a few lines later

   manager.bindMainView(mainViewElement, disableCameraTransform);
        replaceRoomFunction(room, manager.appManager);      
        emitter.emit("onCreated");
        WindowManager.isCreated = true;

however even after running the source, adding debug lines and comments, this property is being set True somewhere else.

can you advise where else i could be looking as to why this property is being set true?

**Comment by l1shen** [comment]
only in `WindowManager.mount` `isCreated ` can be set true

If `WindowManager.mount` fails because isCreated is true, please check if it is because the previous WindowManager instance was not destroyed correctly.
